// Auto-genrated for mc v1.0.0
// Do not edit this file manually!
// Date: 4/17/2023 3:15:58 AM
export type Mat4 = [
  number, number, number, number,
  number, number, number, number,
  number, number, number, number,
  number, number, number, number,
] | Float32Array;
export type Readonly = readonly [
  number, number, number, number,
  number, number, number, number,
  number, number, number, number,
  number, number, number, number,
] | Float32Array;
export function create() {
  const mat = new Float32Array(16);
  mat[0] = mat[5] = mat[10] = mat[15] = 1;
  return mat;
}
